#!/usr/bin/env python3
"""
CityBus — Corporate Staff Provisioning Tool
============================================
Usage:
  python provision_staff.py

This script generates ready-to-run SQL INSERT statements with correctly
hashed passwords. Copy the output and paste it into Supabase SQL Editor.

Never use PostgreSQL's crypt() — it is incompatible with the app's
verify_pw() function which expects the format:  salt:sha256hash
"""

import os
import hashlib
import sys

# ── Same hash_pw as api/index.py ──────────────────────────────────────────────
def hash_pw(pw: str) -> str:
    salt = os.urandom(16).hex()
    return salt + ":" + hashlib.sha256(f"{salt}{pw}".encode()).hexdigest()

# ── Staff to provision ────────────────────────────────────────────────────────
# Add as many entries as needed. role must be: admin | finance | operator
# Leave phone as None if not applicable.
STAFF = [
    # (full_name,            email,                  phone,          password,                   role)
    ("Evander Prodigo",     "EProdigoA@cb.ph",       "09121231234",  "Evilheroinfernalwing1",    "admin"),
    ("Evander Prodigo",     "EProdigoF@cb.ph",       "09987654321",  "Evilheroinfernalwing1",    "finance"),
    ("Evander Prodigo",     "EProdigoO@cb.ph",       "09876543210",  "Evilheroinfernalwing1",    "operator"),

    ("Erin Butial",        "EButialA@cb.ph",        "09234567890",  "Admin123",          "admin"),

    # Add more staff below — copy the line above and change the values:
    # ("Juan Santos",        "JSantos@cb.ph",        "09171234567",  "StrongPass@2026",          "finance"),
    # ("Maria Reyes",        "MReyes@cb.ph",         None,           "AnotherPass@2026",         "operator"),
]

VALID_ROLES = {"admin", "finance", "operator"}

# ── Validation ────────────────────────────────────────────────────────────────
errors = []
for i, (name, email, phone, password, role) in enumerate(STAFF, 1):
    if not name.strip():
        errors.append(f"Row {i}: full_name is empty")
    if "@" not in email:
        errors.append(f"Row {i}: '{email}' doesn't look like a valid email")
    if len(password) < 8:
        errors.append(f"Row {i}: password for {email} is too short (min 8 chars)")
    if role not in VALID_ROLES:
        errors.append(f"Row {i}: role '{role}' is invalid — must be one of {VALID_ROLES}")

if errors:
    print("❌ Fix these issues before generating SQL:\n")
    for e in errors:
        print(f"   • {e}")
    sys.exit(1)

# ── Generate SQL ──────────────────────────────────────────────────────────────
print("=" * 65)
print("  CityBus Staff Provisioning SQL")
print("  Paste into: Supabase → SQL Editor → New query → Run")
print("=" * 65)
print()
print("-- Generated by provision_staff.py")
print("-- Do NOT share this file after generation (contains passwords)\n")

for full_name, email, phone, password, role in STAFF:
    pw_hash = hash_pw(password)
    phone_val = f"'{phone}'" if phone else "NULL"

    print(f"-- {full_name} ({role})")
    print(f"INSERT INTO users (full_name, email, phone, password_hash, role)")
    print(f"VALUES (")
    print(f"  '{full_name}',")
    print(f"  '{email}',")
    print(f"  {phone_val},")
    print(f"  '{pw_hash}',")
    print(f"  '{role}'")
    print(f") ON CONFLICT (email) DO UPDATE")
    print(f"  SET password_hash = EXCLUDED.password_hash,")
    print(f"      role          = EXCLUDED.role,")
    print(f"      full_name     = EXCLUDED.full_name;")
    print()

print("-- Done. Verify with:")
print("SELECT id, full_name, email, role, phone FROM users")
print("WHERE role IN ('admin', 'finance', 'operator')")
print("ORDER BY role, full_name;")
print()
print(f"✅ SQL generated for {len(STAFF)} staff member(s).")
print("   Copy everything between the === lines and run it in Supabase.")